name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
  slack-channel:
    description: 'Slack channel name'
    required: false
    default: '#general'
  github-slack-map:
    description: 'Map GitHub username to Slack user IDs. Eg: "DavideViolante:UABCDEFGH,foobar123:UIHJKLMNO"'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'