name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  webhook-url:
    description: 'Discord Webhook URL'
    required: true
  freeze-date:
    description: 'Feature freeze date'
    required: true
    default: 'slack'
  sc-webhook-url:
    description: 'Service checker webhook url'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'