name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  slack-webook-url:
    description: 'Slack webhook URL'
    required: true
  slack-channel:
    description: 'Slack channel name'
    required: false
    default: '#general'
runs:
  using: 'node12'
  main: 'dist/index.js'